add hall to site angular model
Geekhub-2014-JS/Theatre pull request #25
Opened 2017-02-22 17:01 UTC by kds1660

for now without api requests

2017-02-25 08:31 UTC, Varkh requested changes

2017-02-25 08:31 UTC, Varkh commented on src/js/Controllers/hallCtrl.js
> +        $scope.getUrl=function () {
remove

2017-02-25 08:31 UTC, Varkh commented on src/js/Services/services.js
> +        var hall='';
think about getting list of halls from back-end

2017-02-25 08:31 UTC, Varkh commented on src/js/Services/services.js
> +            console.log(order[index],index)
no `console.log`

2017-03-06 13:21 UTC, Varkh requested changes

2017-03-06 13:21 UTC, Varkh commented on app/views/Performance/performance.html
> +                        <span >Придбати квиток</span>
As I understand, titles should be moved to file. As there are few languages. ex. `{{perfomance.performance.title}}`

2017-03-06 13:21 UTC, Varkh commented on src/js/Controllers/SinglePerfCtrl.js
> +        function ($scope, $q, apiGet, $stateParams, dateConvert, $rootScope,$state,perfomanceService) {
space ` ` before parameter

2017-03-06 13:21 UTC, Varkh commented on src/js/Directives/HallDirective.js
> +
remove unneeded new lines

2017-03-06 13:21 UTC, Varkh commented
Update changed from DEV, as Merging is blocked

2017-03-06 15:53 UTC, kds1660 commented on src/js/Directives/HallDirective.js
> +
removed

2017-03-06 15:53 UTC, kds1660 commented on src/js/Controllers/SinglePerfCtrl.js
> +        function ($scope, $q, apiGet, $stateParams, dateConvert, $rootScope,$state,perfomanceService) {
added spaces

2017-03-06 16:00 UTC, kds1660 commented on src/js/Services/services.js
> +        var hall='';
for now get from backend const halls and add in object
 var hallConst = {
                "Черкаська Філармонія": "Filarmonia",
                "Будинок культури ім. Кулика": "Kulyka",
                "Черкаський Театр": "",
                "Кінотеатр 'Салют'": "",
                "Черкаський міський Палац молоді": "",
                "Центр дитячої та юнацької творчості": ""
            };

2017-03-06 16:43 UTC, kds1660 commented on src/js/Services/services.js
> +        var hall='';
for now dont have api, added from const, backend said, that they
will provide for a venue resource, but how i will convert names into html filename, if i receive halls...

2017-03-06 17:03 UTC, kds1660 commented on app/views/Performance/performance.html
> +                        <span >Придбати квиток</span>
this is strange translation at site, menu-ok, other -50/50. I think about it, i will try translate today, but venue from backend - ukrainian always

2017-03-17 18:27 UTC, Varkh commented
@kds1660  Please, update from dev one more time

2017-03-18 09:20 UTC, Varkh approved these changes

2017-03-18 09:20 UTC, merged