add login modal window in hall page, add 15 min timer
Geekhub-2014-JS/Theatre pull request #28
Opened 2017-03-26 20:26 UTC by kds1660

1. add timer directive/controller, when user add place to cart timer
start (15 minutes), when user empty cart - stop timer , add styles for timer
2. translate for login modal window, timer
3. for social add social button angular module with fonts
3. add modal login page with facebook for now login (send my app id for now, must change) and send login request when modal login window close, else if user dont login

2017-04-03 15:42 UTC, Varkh requested changes

2017-04-03 15:42 UTC, Varkh commented on src/css/hall.css
> +  !important;
what is `!important` here?

2017-04-03 15:42 UTC, Varkh commented on src/js/Controllers/LoginCtrl.js
> +    .controller('LoginCtrl', ['$scope', '$modalInstance','$rootScope', '$facebook', 'apiPost', 'userService',
move to different file: separate config and controller

2017-04-03 15:42 UTC, Varkh commented on src/js/Controllers/LoginCtrl.js
> +                                /*$rootScope.user.accessToken = response.authResponse.accessToken;
no comments in code. remove

2017-04-03 15:42 UTC, Varkh commented on src/js/Controllers/LoginCtrl.js
> +                                // the user isn't logged in to Facebook.
what should be here?

2017-04-03 15:42 UTC, Varkh commented on src/js/Controllers/hallCtrl.js
> +                    "first_name": userService.getCurrentUser().first_name, //Todo to service
You can create ticket for all this TODOs, just don't left them unhandled

2017-04-03 15:42 UTC, Varkh commented on src/js/Controllers/hallCtrl.js
> +            function getTimeRemaining(endtime){
Move to some Util factory

2017-04-03 16:31 UTC, kds1660 commented on src/css/hall.css
> +  !important;
owerwrite standart bootstrap modal white background, without bootstrap css priority highter

2017-04-03 16:33 UTC, kds1660 commented on src/js/Controllers/LoginCtrl.js
> +                                // the user isn't logged in to Facebook.
backend give me api token, thay dont implemented this yet...

2017-04-03 16:34 UTC, kds1660 commented on src/js/Controllers/hallCtrl.js
> +                    "first_name": userService.getCurrentUser().first_name, //Todo to service
I solved them, forget remove

2017-04-03 16:38 UTC, kds1660 commented on src/js/Controllers/LoginCtrl.js
> +    .controller('LoginCtrl', ['$scope', '$modalInstance','$rootScope', '$facebook', 'apiPost', 'userService',
in site config in module file,  I'm sticking to the logic of the site

2017-04-03 16:52 UTC, kds1660 commented on src/js/Controllers/LoginCtrl.js
> +                                // the user isn't logged in to Facebook.
i will remove this and call api get request, when modal window closed

2017-04-03 16:55 UTC, kds1660 commented on src/js/Controllers/hallCtrl.js
> +            function getTimeRemaining(endtime){
Was going to do - timer service for hall and for shopping cart, now remake

2017-04-05 13:38 UTC, Varkh approved these changes

2017-04-05 13:38 UTC, merged