changes in timers, hall template given from backend
Geekhub-2014-JS/Theatre pull request #29
Opened 2017-04-18 19:43 UTC by kds1660

2017-04-27 09:53 UTC, Varkh requested changes

2017-04-27 09:53 UTC, Varkh commented on src/js/Controllers/hallCtrl.js
> +                        console.log(error);
`console.error`

2017-04-27 09:53 UTC, Varkh commented on src/js/Controllers/hallCtrl.js
> +                    endTime.setMinutes(endTime.getMinutes() + 15);
What is 15 here?

2017-04-27 09:53 UTC, Varkh commented on app/views/Hall/Hall.html
> +<script>
Maybe move to separate file?
Will it be used in other halls?

2017-04-27 10:03 UTC, kds1660 commented on app/views/Hall/Hall.html
> +<script>
this is common file for all halls

2017-04-27 10:03 UTC, kds1660 commented on src/js/Controllers/hallCtrl.js
> +                    endTime.setMinutes(endTime.getMinutes() + 15);
customer asked to set 15min timer for buying tickets

2017-04-27 10:06 UTC, kds1660 commented on src/js/Controllers/hallCtrl.js
> +                        console.log(error);
changed

2017-04-27 10:10 UTC, kds1660 commented on src/js/Controllers/hallCtrl.js
> +                    endTime.setMinutes(endTime.getMinutes() + 15);
removed to timeForBuy variable

2017-04-27 12:05 UTC, kds1660 commented on app/views/Hall/Hall.html
> +<script>
popover didn't work, i forget that receive hall from backend now and must call after response success, remove function in file and call it when template loading nowpopover didn't work, i forget that receive hall from backend now and must call after response success, remove function in file and call it when template loading now

2017-05-15 19:07 UTC, spolischook approved these changes

2017-05-15 19:11 UTC, merged